### Obtener todas las mascotas
GET http://localhost:5000/mascotas HTTP/1.1
Content-Type: application/json

###

### Obtener una mascota por ID
GET http://localhost:5000/mascotas/1 HTTP/1.1
Content-Type: application/json

###

### Crear una nueva mascota
POST http://localhost:5000/mascotas HTTP/1.1
Content-Type: application/json

{
    "nombre": "Luna",
    "especie": "Perro",
    "raza": "Labrador",
    "edad": 3,
    "descripcion": "Amigable y enérgica.",
    "estado": "disponible"
}

###

### Actualizar una mascota existente
PUT http://localhost:5000/mascotas/1 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Luna",
    "especie": "Perro",
    "raza": "Labrador",
    "edad": 4,
    "descripcion": "Amigable y muy activa.",
    "estado": "disponible"
}

###

### Eliminar una mascota
DELETE http://localhost:5000/mascotas/6 HTTP/1.1
Content-Type: application/json

###solicitudes----------------------------------------------------------


### Obtener todas las solicitudes
GET http://localhost:5000/solicitudes HTTP/1.1
Content-Type: application/json

###

### Obtener una solicitud por ID
GET http://localhost:5000/solicitudes/1 HTTP/1.1
Content-Type: application/json

###

### Crear una nueva solicitud
POST http://localhost:5000/solicitudes HTTP/1.1
Content-Type: application/json

{
    "mascota_id": 1,
    "nombre_solicitante": "Juan Pérez",
    "email_solicitante": "juan.perez@example.com",
    "telefono_solicitante": "3501234567",
    "fecha_solicitud": "2024-09-20T10:00:00Z",
    "estado": "pendiente"
}

###

### Actualizar una solicitud existente
PUT http://localhost:5000/solicitudes/1 HTTP/1.1
Content-Type: application/json

{
    "estado": "aprobada"
}

###

### Eliminar una solicitud
DELETE http://localhost:5000/solicitudes/1 HTTP/1.1
Content-Type: application/json

###
